### ISSUE TITLE
Inbound rule does not work with ExpressionChangedAfterItHasBeenCheckedError console error 

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#229]
If I start IIS.WebManager standalone (without using WAC), The Inbound rule UI of Url-Rewrite does not work showing below console error.
FYI, this issue was happening only after the last commit. 

```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.


Function code (234) (98,3)

[object Error]: {description: "ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.", message: "ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.", ngDebugContext: Object, ngErrorLogger: function() { [native code] }, stack: "Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'. at checkBindingNoChanges (eval code:10145:9) at checkNoChangesNodeInline (eval code:14199:9) at checkNoChangesNode (eval code:14173:9) at debugCheckNoChangesNode (eval code:15002:24) at debugCheckDirectivesFn (eval code:14904:13) at Anonymous function (Function code:148:5) at debugUpdateDirectives (eval code:14886:5) at checkNoChangesView (eval code:14011:5) at callViewAction (eval code:14364:21) at execComponentViewsAction (eval code:14316:13)"}
```

**Comment by shhsu** [comment]
After some investigations, I think the issue is not exactly as stated. The blank page should have nothing to do with the ExpressionChangedAfterItHasBeenCheckedError.

Before https://github.com/Microsoft/IIS.WebManager/pull/259, notification service does not work. If website configuration is not able to load (for example, web.config) does not exist, the page loading would fail silently. Right now, the behavior is as shown.

Right now, the screen would look like this

![image](https://user-images.githubusercontent.com/6619915/52309547-5403b980-2955-11e9-98e0-b32f222f83c2.png)
