### ISSUE TITLE
Non standard UI controls should be replaced with WAC SDK controls

### ISSUE THREAD

**Issue by shhsu** [Microsoft/IIS.WebManager#236]
We should use WAC SDK controls as much as possible to fix known accessibility issues. 

#198 (Non standard UI, Won't fix)
#181 (Non standard UI, Won't fix)
#91 (Non standard UI, Won't fix)
#94 (Non standard UI, Won't fix)
#116 (Non standard UI, Won't fix)
#159 (Non standard UI, Won't fix)
#173 (Non standard UI, Won't fix)
#107 (Non standard UI, Won't fix)

**Comment by jhkimnew** [comment]
Verify below issues when this issue is fixed:

https://github.com/Microsoft/IIS.WebManager/issues/212
https://github.com/Microsoft/IIS.WebManager/issues/198
https://github.com/Microsoft/IIS.WebManager/issues/184
https://github.com/Microsoft/IIS.WebManager/issues/181
https://github.com/Microsoft/IIS.WebManager/issues/170
https://github.com/Microsoft/IIS.WebManager/issues/63
https://github.com/Microsoft/IIS.WebManager/issues/73
https://github.com/Microsoft/IIS.WebManager/issues/86
https://github.com/Microsoft/IIS.WebManager/issues/91
https://github.com/Microsoft/IIS.WebManager/issues/94
https://github.com/Microsoft/IIS.WebManager/issues/100
https://github.com/Microsoft/IIS.WebManager/issues/109
https://github.com/Microsoft/IIS.WebManager/issues/175
https://github.com/Microsoft/IIS.WebManager/issues/133
https://github.com/Microsoft/IIS.WebManager/issues/128
https://github.com/Microsoft/IIS.WebManager/issues/125
https://github.com/Microsoft/IIS.WebManager/issues/116
https://github.com/Microsoft/IIS.WebManager/issues/159
https://github.com/Microsoft/IIS.WebManager/issues/173
https://github.com/Microsoft/IIS.WebManager/issues/164
https://github.com/Microsoft/IIS.WebManager/issues/145
https://github.com/Microsoft/IIS.WebManager/issues/136
https://github.com/Microsoft/IIS.WebManager/issues/107
https://github.com/Microsoft/IIS.WebManager/issues/81
https://github.com/Microsoft/IIS.WebManager/issues/76

**Comment by jhkimnew** [comment]
Closing...
This work item can be revisited actually when we work on this and don't need to keep this issue opened..
