### ISSUE TITLE
Permission issue after installing IIS Administration API via IIS.WebManager WAC extension

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#263]
REPRO:
1.	Run below script from powershell 

```
cd "C:\Program Files\IIS Administration"
md temp 
$old = get-acl .\2.2.0\
set-acl .\temp $old

$dirAcl = get-acl .\temp
$rights = [System.Security.AccessControl.FileSystemRights]::Traverse `
 -bOr [System.Security.AccessControl.FileSystemRights]::Modify `
 -bOr [System.Security.AccessControl.FileSystemRights]::ChangePermissions

$inheritFlags = [System.Security.AccessControl.InheritanceFlags]::ContainerInherit `
 -bOr [System.Security.AccessControl.InheritanceFlags]::ObjectInherit
$propFlags = [System.Security.AccessControl.PropagationFlags]::InheritOnly
$ar = New-Object System.Security.AccessControl.FileSystemAccessRule("BUILTIN\Administrators", $rights, $inheritFlags, $propFlags, "allow")
$dirAcl.SetAccessRule($ar) | Out-Null
Set-Acl -Path .\temp -AclObject $dirAcl | Out-Null
```
2.	Open Permissions for temp folder and check the updated ACL for administrators 

EXPECTED:

Permissions for Administrators is shown

ACTUAL:

Permissions for Administrators is shown empty like the below screenshot.

![image](https://user-images.githubusercontent.com/20650163/51064673-b3201980-15b5-11e9-85af-8a962895e059.png)

**Comment by shhsu** [comment]
Note that Get-Acl actually returns that administrators has modify permissions of the directory.

**Comment by jhkimnew** [comment]
@shhsu This issue is originally found by another issue. Suddenly I was not able to restart the IISAdministration API windows service after changing owner of the installation folder because I was not able to open the folder after installing the IIS.WebAdministration WAC extension. 
The reason why I changed the owner is to update the appsettings.json file to configure the IIS.Administration API. 

Before this issue, I was able to do that with changing only the owner of the appsettings.json file and that's why I opened this issue in order to fix the two issues together.

**Comment by shhsu** [comment]
After some investigation. I am seeing this issue as a "won't fix". The reason is as below:

* Our build script by, design remove the explicit permission of the installer (in your case jhkim@windows.microsoft.com) The reason being we don't want to treat the original installer of the API any differently as any other administrator.

* You need "explicit" permission to use file explorer to view the content and permission of the directly. Meaning after deleting jhkim@windows.microsoft.com you have lost access to manually access and modify the directory and its content.

Any edits of the configuration needs to be done via a tool we provided. User is not supposed to manually change permissions and mess with our config file

**Comment by jhkimnew** [comment]
@shhsu If users are not supposed to change the permission, I think we should update the existing documentation https://docs.microsoft.com/en-us/iis-administration/configuration/appsettings.json#default-settings. That does not explain clearly about that and I thought users are allowed to update the appsettings.json file. I will open a doc bug.
