### ISSUE TITLE
Move server actions from drop-down into a separate overview page

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/IIS.WebManager#266]
![image](https://user-images.githubusercontent.com/4734691/51138259-7e9aa080-17f5-11e9-978b-dde63ca6ccf2.png)

![image](https://user-images.githubusercontent.com/4734691/51138263-80fcfa80-17f5-11e9-8902-fb28d8af7d78.png)

**Comment by tanyastockland** [comment]
Use this image instead for reference. I used the wrong icon for Start and updated the breadcrumb name.
![2 iis web server general](https://user-images.githubusercontent.com/46721345/51196780-b01e7500-18a4-11e9-89e1-b100c415956d.png)

**Comment by shhsu** [comment]
Currently have drop down on webserver, app-pool, and website. The motivation this fix is that the drop down could be confusing if user are used to WAC's style of start/stop button.

If we remove the drop down for webserver, should we remove them from app-pool and website page?

**Comment by tanyastockland** [comment]
The idea was to have the Restart/Start/Stop only in the Web Server Overview. So yes, remove from app-pool and website page. Thanks!

**Comment by shhsu** [comment]
I wonder if it would be ok if we have the start/stop command buttons placed on the right side of the breadcrumbs. If so, I want to move these buttons after I finish working on the breadcrumbs

**Comment by tanyastockland** [comment]
That might be a little weird and confusing to the user to have the command / action buttons next to the breadcrumb. Do you want it there so that it’s always visible no matter where the user is?

@Haley<mailto:harowl@microsoft.com> didn’t we discuss having the action buttons just on the Web Server Overview?

**Comment by ghost** [comment]
Yes, @tanyastockland & @shhsu we had decided to only keep the restart/start/stop only in Web Server Overview and to remove it from any other breadcrumbs. Since it's a rather heavy-weight operation to restart/stop/start the Web Server itself, we feel it is okay to put this functionality only in the overview page and hide from other pages.
