### ISSUE TITLE
Ensure that Features that aren't enabled notify you so

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/IIS.WebManager#273]
![image](https://user-images.githubusercontent.com/4734691/51139433-be16bc00-17f8-11e9-8f65-b0af85094f1d.png)

**Comment by shirhatti** [comment]
Eventually we'd want to deep link to the Windows Features page in WAC

**Comment by shirhatti** [comment]
This is probably below the cut line for the preview

**Comment by shhsu** [comment]
This problem is already fixed by, right now the behavior is as followed

if feature is not enabled, you will see
![image](https://user-images.githubusercontent.com/6619915/52368979-828c9d80-2a04-11e9-9ee5-59764a911685.png)

Switching the toggle installs the feature

![image](https://user-images.githubusercontent.com/6619915/52369002-90422300-2a04-11e9-8d55-d4b1350d5373.png)
