### ISSUE TITLE
Usability issue regarding breadcrumb bar

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#400]
1.	Currently there is no way to go to the server level when the navigation bar is disappeared as the below screenshot. We should consider making it clickable.
2.	When selecting the current object node such as “Default Web Site” in the below screenshot, it does no-action. Maybe we should not make it clickable or we should enable it in non-General page and let it go to the General page

![image](https://user-images.githubusercontent.com/20650163/60042439-96aeff80-9672-11e9-9b3d-90bc31c569a3.png)

**Comment by shhsu** [comment]
My proposal:
* Put the link to "IIS Web Server" root element back. It would now "always" be clickable and navigate to webserver/general page.
* When on "general" page, instead of "IIS Web Server > Web Sites > Default Web Site > General". We show "IIS Web Server > Web Sites > Default Web Site", last element "Default Web Site" is not clickable.
Same for Web App and App Pool.
* When on feature page. "IIS Web Server > Web Sites > Default Web Site > Authentication", the last element "Authentication" is not clickable but "Default Web Site" bring you to web site's general page

**Comment by jhkimnew** [comment]
@shhsu, FYI closing this...
